blueprint:
  name: No presense Auto-Shutoff Timer
  description: Home Assistant Blueprint that automates smart plug shutoff based on a configurable device state within a defined time window for energy efficiency. Extends CWagner's initial Blueprint

  domain: automation
  input:
    trigger_device:
      name: Trigger Device
      description: Choose a device_tracker or binary_sensor to trigger the automation.
      selector:
        entity:
          domain: 
            - device_tracker
            - binary_sensor
    trigger_state:
      name: Trigger State
      description: Configurable state of the trigger device to initiate the automation.
      default: 'off'
    smart_plug_switch:
      name: Target Smart Plug
      description: This smart plug will be turned off once the condition is met.
      selector:
        entity:
          domain: switch
    off_delay:
      name: Wait Time
      description: Time the device needs to be in the trigger state for the automation to trigger.
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
    time_window_start:
      name: Time Window Start
      description: Start time of the window during which the automation is allowed to run.
      default: '22:00:00'
      selector:
        time: {}
    time_window_end:
      name: Time Window End
      description: End time of the window during which the automation is allowed to run.
      default: '06:00:00'
      selector:
        time: {}
    check_state:
      name: Check State
      description: Enable or disable the state check within the actions.
      default: true
      selector:
        boolean: {}
trigger:
  - platform: state
    entity_id: !input trigger_device
    to: !input trigger_state
    for:
      minutes: !input off_delay
  - platform: time_pattern
    minutes: '/1'
condition:
  - condition: time
    after: !input time_window_start
    before: !input time_window_end
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_state(trigger_device, trigger_state) }}"
        sequence:
          - service: switch.turn_off
            data:
              entity_id: !input smart_plug_switch
    default: []
  - condition: template
    value_template: "{{ is_state(trigger_device, trigger_state) or not check_state }}"
  - service: switch.turn_off
    data:
      entity_id: !input smart_plug_switch
mode: single
