blueprint:
  name: No presense Auto-Shutoff Timer
  description: Automates smart plug shutoff 10 minutes after the defined time window starts or after the device turns off within the time window for energy efficiency. Extends CWagner's initial Blueprint.

  domain: automation
  input:
    trigger_device:
      name: Trigger Device
      description: Choose a binary_sensor to trigger the automation.
      selector:
        entity:
          domain: binary_sensor
    smart_plug_switch:
      name: Target Smart Plug
      description: This smart plug will be turned off 10 minutes after the condition is met.
      selector:
        entity:
          domain: switch
    time_window_start:
      name: Time Window Start
      description: Start time of the window during which the automation is allowed to run.
      default: '22:00:00'
      selector:
        time: {}
    time_window_end:
      name: Time Window End
      description: End time of the window during which the automation is allowed to run.
      default: '06:00:00'
      selector:
        time: {}

trigger:
  - platform: time
    at: input_datetime.time_window_start
  - platform: state
    entity_id: !input trigger_device
    to: 'off'
    for:
      minutes: 10

condition:
  - condition: time
    after: !input time_window_start
    before: !input time_window_end

action:
  - service: switch.turn_off
    target:
      entity_id: !input smart_plug_switch

mode: single
